import type { Metadata } from 'next';
import { Red_Hat_Display } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';

const redHatDisplay = Red_Hat_Display({
  variable: '--font-red-hat-display',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className={cn(
        'h-full scroll-smooth',
        'antialiased',
        redHatDisplay.variable
      )}
    >
      <body>
        <div className='max-w-360 m-auto w-full flex flex-col min-h-full'>
          {children}
        </div>
      </body>
    </html>
  );
}
